apiVersion: v2
name: seamless-world
description: Infrastructure of the seamless world demo in Kubernetes

type: application

# This is the chart version. 
version: 0.1.0

# This is the version number of application.
appVersion: "1.0.0"

dependencies:
  - name: nats
    version: "1.2.1"
    repository: "https://nats-io.github.io/k8s/helm/charts/"