apiVersion: v1
kind: Service
metadata:
  name: dynamodb-admin
  labels:
    app: dynamodb-admin
spec:
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: dynamodb-admin
  type: LoadBalancer
