apiVersion: v1
kind: Service
metadata:
  name: nats-service
  labels:
    app: nats-service
spec:
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: app
  type: LoadBalancer
