apiVersion: v1
kind: Service
metadata:
  name: {{ include "seamless-world.fullname" . }}-redis
  labels:
    {{- include "seamless-world.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seamless-world.fullname" . }}-redis-lb
  labels:
    {{- include "seamless-world.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
